MicrosoftDocs/Virtualization-Documentation

windows-server-container-samples/README.md
Merging in place for windows container samples
=> adding a place for samples!

doc-site/virtualization/hyperv_on_windows/user_guide/migrating_vms.md
Adding reference to the fact that you can use the UI, fixing PowerShell
command
=> Updating VM upgrade information

windows-server-container-samples/iis-10.0/Dockerfile, windows-server-container-samples/iis-10.0/HybridInstaller.ps1, windows-server-container-samples/iis-10.0/README.md, windows-server-container-samples/node-v0.12.7-x64/Dockerfile, windows-server-container-samples/node-v0.12.7-x64/HybridInstaller.ps1, windows-server-container-samples/node-v0.12.7-x64/README.md
Adding samples how to create an IIS image and how to create a node.js image using PowerShell or Docker managed Windows Server Containers
=> Added Container Image creation samples

windows-server-container-tools/VMM  - VM Template/AdminAutoLogon.xml, windows-server-container-tools/VMM  - VM Template/ContainerHostTemplate.xml
Contains the VM template that users will need to download to create a
Windows Container Host.
=> VM Template for VMM users to try out Windows Containers

hyperv-tools/Convert-WindowsImage/Convert-WindowsImage.ps1
Strict mode, better handling for UEFI ESP
=> Incorporate updates from the Nano team

hyperv-tools/Nested/Enable-NestedVm.ps1
Wanted to add a few things people were confused on into the script, also fixed a few minor issues.
=> Check for memory size and mac address in nested scripts.

virtualization/windowscontainers/containers_welcome.md
Reverts Microsoft/Virtualization-Documentation#83
=> Revert "Update containers_welcome.md"

virtualization/windowscontainers/deployment/deployment.md
Fixing the Container OS Image Version to the published version.
=> Fixing the Container OS Image Version

virtualization/community/contribute_to_docs.md
Adding a sentence about commit request conventions.
=> Clarified pull request instructions

hyperv-tools/Nested/Enable-NestedVm.ps1
Change the if to set VM Memory, the answer 'N' or 'n' was not supported.
=> Memory question correction and spelling correction

virtualization/hyperv_on_windows/windows_welcome.md, virtualization/windowscontainers/quick_start/manage_powershell.md
add an example of listing existing containers (using the Get-Container command).
=> Patch to add an example of using Get-Container

virtualization/windowscontainers/management/hyperv_container.md
=> Minor command spelling fix

virtualization/windowscontainers/about/work_in_progress.md
'affectively' changed to 'effectively'
=> Fixed typo in work_in_progress.md

virtualization/windowscontainers/management/container_networking.md, virtualization/windowscontainers/management/manage_containers.md
=> Patrick lang patch 1

virtualization/windowscontainers/quick_start/manage_docker.md
The "Configure Network" section has a powershell instruction but powershell.exe part is missing from it. This results in error when this instruction is use as-is.
=> Configure Network section instruction needs an update

virtualization/windowscontainers/about/faq.md
The H4 headings looked awful rendered
=> Reorganized FAQ

virtualization/windowscontainers/reference/ps_docker_comparison.md
Added missing link to docker management api. 
Regards,
Razi
=> Missing link to docker management api

windows-server-container-tools/DockerTLS/readme.md
=> Readme.md for Initial Commit of Docker TLS Scripts

windows-server-container-tools/DockerTLS/DockerCertificateTools.ps1, windows-server-container-tools/DockerTLS/readme.md
Thanks @taylorb-microsoft for the TLS script.
I've followed the steps in the README and found only two minor improvements to make it work.
=> Source script and initialize $keyPath

virtualization/windowscontainers/deployment/deployment_nano.md
How to connect to the container host and install the Docker daemon was lacking, so added information about the `-VMName` parameter now defined on `Enter-PSSession` after following these instructions.
=> Add method to connect to container host

hyperv-tools/Convert-WindowsImage/Convert-WindowsImage.ps1
- Fixes #185
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/microsoft/virtualization-documentation/186)
=> Fix Error message in Convert-WindowsImage when Edition is not found in WIM file - Fixes #185

hyperv-tools/Convert-WindowsImage/Convert-WindowsImage.ps1
Add-PartitionAccessPath does not support concurrent calls.
=> Adding re-try logic around Add-PartitionAccessPath

windows-server-container-tools/DockerTLS/DockerCertificateTools.ps1
@taylorb-microsoft @neilpeterson @jstarks @jterry75 
This change introduces an extra step in New-ClientKeyandCert that will create the pfx file needed for Windows certificate code, specifically the .NET class X509Certificate2.  This will be used to enable TLS support for the upcoming PowerShell cmdlets.
Signed-off-by: Stefan J. Wernli <swernli@microsoft.com>
=> Updating script to automatically produce pfx file for Windows use.

virtualization/windowscontainers/deployment/deployment.md
there was a $ instead of a # when the script run will wine about it
=> typo in the Enable nested virtualization script

virtualization/windowscontainers/deployment/deployment.md, virtualization/windowscontainers/management/manage_images.md
I have seen some cases on forums where someone found instructions to add the ContainerImage provider and install a base OS image, but didn't know to restart the Docker daemon. This clarifies it.
=> Clarify that docker restart is needed after adding images.

virtualization/hyperv_on_windows/about/whats_new.md
=> Changed whats_new.md in virtualization/hyperv_on_windows/about

virtualization/windowscontainers/quick_start/container_setup.md
=> Some improvements

virtualization/hyperv_on_windows/about/hyperv_on_windows.md, virtualization/hyperv_on_windows/about/whats_new.md
Formatting and wording changes for clarity, plus a little copy-editing.
=> "Hyper-V on Windows" cleanup

windows-container-samples/windowsservercore/iis/README.md
Should have updated the documentation README with previous PR, apologies.
=> updated README.md with new CMD statement

virtualization/hyperv_on_windows/user_guide/checkpoints.md, virtualization/hyperv_on_windows/user_guide/export_import.md, virtualization/hyperv_on_windows/user_guide/vmsession.md
Hope this helps...
Regards,
Kurt Roggen [BE]
=> Some suggestions and corrections of typos

virtualization/hyperv_on_windows/user_guide/vmsession.md
Corrected parameter -VMId instead of -VMGuid
=> Update for parameters -VMId

hyperv-tools/DiscreteDeviceAssignment/SurveyDDA.ps1
Changes include returning the devices required MMIO space.
Note, this file was moved from Ben Armstrong's personal git repository to
the tool's repository for HyperV
=> Added updated SurveyDDA.ps1 script.

windows-container-samples/windowsservercore/sqlserver-express/2014sp1/Dockerfile
Finally came up with a sql server express dockerfile that's not embarrassing.
cc @PatrickLang @brogersyh
=> add sqlserver express dockerfile

virtualization/windowscontainers/quick_start/quick_start_windows_10.md
I didn't think there was a Windows Server 10 so it's a little confusing when first reading about this.
=> Windows 10 or Windows Server 10?

windows-container-samples/windowsservercore/apache-http-php/dockerfile
Previous version's vc11 and php cannot be downloaded.
=> Update docker file apache-http-php software versions

virtualization/hyperv_on_windows/user_guide/vmsession.md
Peristant -> Persistant - Line 21
=> Spelling correction vmsession.md

virtualization/windowscontainers/docker/manage_windows_dockerfile.md
According to feedback from @friism in the https://github.com/docker/docker/issues/22921#issuecomment-221109082 comment
=> Add info on how to install Windows Installer files

virtualization/windowscontainers/deployment/system_requirements.md
=> Updating image support matrix

virtualization/windowscontainers/deployment/system_requirements.md
Reverts Microsoft/Virtualization-Documentation#337
=> Revert "Updating image support matrix"

hyperv-tools/Convert-WindowsImage/Convert-WindowsImage.psm1
`-DiskLayout BIOS` was exiting with error and failing to complete bcdboot and remainder of script. Added `BIOS` to if statement. Tested, working.
=> Fixes #335

virtualization/windowscontainers/management/container_networking.md
Explains what is the value for com.docker.network.windowsshim.interface
Maybe it's clear for most people, but my first attempt was to get value from
```
ipconfig
```
not from 
```
Get-NetAdapter
```
Maybe it will help others avoid my mistake.
=> Value for com.docker.network.windowsshim.interface

virtualization/hyperv_on_windows/user_guide/remote_host_management.md
Allow "delegating" fresh credentials with NTLM-only server authentication
Instead of
Allow fresh credentials with NTLM-only server authentication
Thank You!
=> Small Typo Update

windows-container-samples/windowsservercore/apache-http-php/Dockerfile
=> Fixed typo in vendor

windows-container-samples/windowsservercore/apache-http-php/README.md
Fixed typo: Same in the README
=> Fixed typo: Same in the README

virtualization/windowscontainers/quick_start/quick_start_windows_server.md
=> Bump Docker version to 1.12.1

virtualization/hyperv_on_windows/user_guide/remote_host_management.md
=> Correctons about downlevel platforms

virtualization/windowscontainers/docker/configure_docker_daemon.md
sc config docker binpath= "\"C:\Program Files\docker\dockerd.exe\" --run-service -H tcp://0.0.0.0:2375" only works inside cmd.exe
=> Update configure_docker_daemon.md - "sc config docker binpath" usage

virtualization/windowscontainers/quick_start/quick_start_windows_10.md
This addresses #392, and can replace PR #393
=> Clarify minimum patch version for Windows 10

virtualization/hyperv_on_windows/user_guide/checkpoints.md
I noticed a few typos and updated the text where necessary.
=> Fix some typos

virtualization/windowscontainers/deployment/deployment.md
Good catch Neil - staging the changes in the other docs now.
Do we want to call out "If you've already installed Docker, you can skip to step 2"?
=> STAGING changes to docs for OneGet Provider

virtualization/windowscontainers/deployment/deployment_nano.md
I'm not as familiar with the Nano flow so a few questions:
1. Will the Docker client be installed on Nano? Would it even function?
2. Is there anything peculiar to remote PS management I didn't call out?
=> STAGING changes for introducing OneGet

windows-server-container-tools/Debug-ContainerHost/Debug-ContainerHost.ps1
Resolves #425 - allows 0 or not present
=> Change VSmbDisableOplocks check to 0 or not present

virtualization/hyperv_on_windows/user_guide/remote_host_management.md
Enable remote management from Server Manager and not from System Properties/
Select: "Enable remote management of this server from other computers".
Reference: https://technet.microsoft.com/en-us/library/hh921475.aspx
Thank You!
=> Enable remote management from Server Manager

windows-container-samples/mysql/Dockerfile
my invoke-webrequest cannot follow redirects
default timeout is only 100 seconds, it took several minutes here....
=> Update Download link to CDN, increase timeout

virtualization/windowscontainers/docker/configure_docker_daemon.md
Updated sentence based on John's suggestion.
=> Graph example under docker configuration section

virtualization/windowscontainers/quick_start/quick_start_windows_server.md
@enderb-ms or @mylesbkeating1993 can you double check this? It works for me but I'd like a second look :)
=> Add ARM template link

demos/2016-Ignite-Dive-Into-Shielded-VMs/readme.md
=> Missing the Directory Source path for Windows ADK

virtualization/windowscontainers/deployment/deployment_nano.md
through powershell remoting TTY limitations
=> make notice of current TTY limitations

virtualization/windowscontainers/quick_start/quick_start_windows_server.md
- Move repo link to the new one maintained by the .NET Team.
=> Update dotnet sample

virtualization/windowscontainers/quick_start/quick_start_windows_10.md
Docker removed build 1.13 from download location, updated to 1.14
=> 1.13 ==> 1.14

windows-server-container-tools/Debug-ContainerHost/Debug-ContainerHost.ps1, windows-server-container-tools/Debug-ContainerHost/README.md
Checks that Docker is registered in the EventLog service
=> Finds error #502

virtualization/windowscontainers/docker/manage_windows_dockerfile.md
From time to time I encounter slow download rates with `Invoke-WebRequest`. Today I realised that PowerShell is on GitHub and found https://github.com/PowerShell/PowerShell/issues/2138.
After testing it in a `Dockerfile` with `docker build` I found out that the invisible progressbar also impacts download speed inside a Windows container. So it is important to use `$ProgressPreference = 'SilentlyContinue'` to achieve faster download rates.
```Dockerfile
RUN powershell.exe -Command \
$ErrorActionPreference = 'Stop'; \
$ProgressPreference = 'SilentlyContinue'; \
Invoke-WebRequest https://www.python.org/ftp/python/3.5.1/python-3.5.1.exe -OutFile c:\python-3.5.1.exe ; \		   Invoke-WebRequest https://www.python.org/ftp/python/3.5.1/python-3.5.1.exe -OutFile c:\python-3.5.1.exe
```
Tested …
=> Add $ProgressPreference = 'SilentlyContinue' to improve Invoke-WebRequest

virtualization/windowscontainers/quick_start/quick_start_windows_10.md
It's time to `s/rc2/rc3/g` as v1.13 moves along.
Any objections @enderb-ms @friism or @jhowardmsft?
=> It's Docker v1.13-RC3 time!

virtualization/windowscontainers/quick_start/quick_start_windows_10.md
A new release candidate Docker 1.13.0-rc4 is available.
=> Update Docker 1.13.0-rc4

windows-server-container-tools/CleanupContainerHostNetworking/CleanupContainerHostNetworking.ps1, windows-server-container-tools/CleanupContainerHostNetworking/README.md, windows-server-container-tools/Debug-ContainerHost/Debug-ContainerHost.ps1
Added some new NAT networking checks for internal vNIC, host vNIC with NAT gateway IP assigned, etc to Debug-ContainerHost.ps1
Also created new networking clean-up and log collection script
=> New Networking Diagnostics

virtualization/windowscontainers/manage-containers/container-networking.md
Removed some options from unsupported features list.
Removed firewall section (out of date)
Added reminder to use most current Docker version.
=> RS1 updates

windows-server-container-tools/Debug-ContainerHost/Debug-ContainerHost.ps1, windows-server-container-tools/Debug-ContainerHost/README.md
=> Adding containers role check

virtualization/hyper-v-on-windows/reference/integration-services.md
=> Removed whitespace

hyperv-tools/ic-update/offline-update-guest.ps1, hyperv-tools/root-memory-reserve/clear-MemoryReserve-regkey.ps1, hyperv-tools/root-memory-reserve/readme.md
This script will be paired with a blog post talking about root memory reserve.
=> Adding a script to remove the MemoryReserve registry key

virtualization/windowscontainers/quick-start/quick-start-windows-10.md
Update the installation steps on Windows 10 to download Docker 1.13.0.
=> Update Docker 1.13.0

virtualization/windowscontainers/about/index.md
remove text that doesn't help explain the topic
Containers are another type of virtualization, also referred to as OS Virtualization. 
Mark Russinovich
@squillace
=> system is too vague

virtualization/windowscontainers/about/index.md
Intro says nothing about windows containers.
@squillace I'd work on the rest of this but the intro has to go.
I don't agree that a container is virtualization.  You don't have virtual network drivers.
=> remove intro

virtualization/windowscontainers/deploy-containers/deploy-containers-on-server.md
ACOM uses sentence casing for headings - you might want to fix that.
=> Remove dead wood and incorrect link

virtualization/hyper-v-on-windows/quick-start/connect-to-network.md
Added a second step to actually select the server first in Hyper-V Manager.
=> Added step to Create a Virtual Switch with Hyper-V Manager

windows-server-container-tools/Debug-ContainerHost/Debug-ContainerHost.ps1
Added a check for the registry key FDVDenyWriteAccess found in #355 and #530 
I only tested i on a single machine without domain join and group policies.
@JanneRantala could you give it a try when you bring one machine back into the state that it can't pull images?
```
wget -UseBasicParsing https://github.com/StefanScherer/Virtualization-Documentation/raw/9637498efd67b4dcdf8f634aa30f142e3c2d99b5/windows-server-container-tools/Debug-ContainerHost/Debug-ContainerHost.ps1 | iex
```
=> Add check for FDVDenyWriteAccess

windows-server-container-tools/Debug-ContainerHost/README.md
=> Adding description for FDVDenyWriteAccess check

windows-server-container-tools/Debug-ContainerHost/Debug-ContainerHost.ps1
This is an attempt to resolve #565
=> Resolving #565 - changing client check in Debug-ContainerHost

virtualization/hyper-v-on-windows/quick-start/enable-hyper-v.md
Missing an `l` in enabled (first paragraph).
=> Fixed spelling error

virtualization/windowscontainers/quick-start/quick-start-windows-server.md
@dwaiba pointed out that the steps won't upgrade to the latest version of Docker in #580 . I'm proposing adding this as a tip to clarify how to check for and install new versions.
=> Upgrade steps using OneGet provider

windows-server-container-tools/Debug-ContainerHost/Debug-ContainerHost.ps1
=> Adding Docker for Windows daemon log path

virtualization/windowscontainers/troubleshooting.md
To save me having to keep repeating this information...
=> Add more debugging information

windows-server-container-tools/CleanupContainerHostNetworking/CleanupContainerHostNetworking.ps1
Script is currently incompatible with overlay -- overlay networks must be removed from system.
If reboot is required, now asks user if restart can occur now. Also reminds user not to run docker commands until after reboot.
=> Additions for better usability: Overlay incompatibility and force restart

hyperv-tools/ic-update/offline-update-host.ps1
In line 23, there should be a space between "Dismount-VHD" command and "-Path" parameter.
=> Fix error in offline-update-host.ps1

virtualization/windowscontainers/manage-containers/container-networking.md
It says "will be will be".  :)
=> Minor fix on container-networking.md

virtualization/windowscontainers/manage-docker/configure-docker-daemon.md
* Fixed URL path of Docker master branch builds
* Beautify system path of Docker Configuration File
=> Fixed URL path of Docker master branch builds

virtualization/windowscontainers/quick-start/Nano-RS3-.NET-Core-and-PS.md
need to edit more when the link to dockerfiles are confirmed.
=> update dockerfile link

virtualization/windowscontainers/quick-start/Nano-RS3-.NET-Core-and-PS.md
Point to .net core and PS dockerfiles so that it is in sync.
=> Update .net core and PS dockerfiles

windows-container-samples/iis-arr/Dockerfile
The comment in the dockerfile contained a new-line which caused the docker build command to fail.
=> Removed a new line which broke the docker file

virtualization/windowscontainers/deploy-containers/system-requirements.md
- Product branding tweaks
- Nano and .NET Core clarification
- Minor wording changes
- Additional links
@cwilhit
=> Feedback on nano vs. server core

virtualization/windowscontainers/quick-start/building-sample-app.md
Fixed minor typos. should be myasp and not myapp
=> corrected the incorrect image passed to docker inspect command

hyperv-tools/HyperVLogs/HyperVLogs.psm1
This PowerShell module can help to enable/disable Windows event channels that are frequently used when analyzing failures in a Hyper-V environment
=> Added PowerShell module to help with log collection

virtualization/hyper-v-on-windows/user-guide/nested-virtualization.md, virtualization/hyper-v-on-windows/user-guide/setup-nat-network.md, virtualization/windowscontainers/deploy-containers/deploy-containers-on-server.md, virtualization/windowscontainers/deploy-containers/system-requirements.md, virtualization/windowscontainers/deploy-containers/version-compatibility.md, virtualization/windowscontainers/manage-containers/container-base-images.md, virtualization/windowscontainers/manage-containers/container-networking.md, virtualization/windowscontainers/manage-containers/hyperv-container.md, virtualization/windowscontainers/manage-containers/manage-serviceaccounts.md, virtualization/windowscontainers/manage-containers/swarm-mode.md, virtualization/windowscontainers/manage-docker/configure-docker-daemon.md, virtualization/windowscontainers/manage-docker/manage-windows-dockerfile.md, virtualization/windowscontainers/manage-docker/optimize-windows-dockerfile.md, virtualization/windowscontainers/quick-start/Nano-RS3-.NET-Core-and-PS.md, virtualization/windowscontainers/quick-start/Using-Insider-Container-Images.md, virtualization/windowscontainers/quick-start/quick-start-images.md, virtualization/windowscontainers/quick-start/quick-start-windows-10.md, virtualization/windowscontainers/quick-start/quick-start-windows-server.md, virtualization/windowscontainers/troubleshooting.md, windows-container-samples/apache-http-php/README.md, windows-container-samples/iis-https/README.md, windows-server-container-tools/Debug-ContainerHost/README.md, windows-server-container-tools/ServiceAccounts/README.md, windows-server-container-tools/Wait-Service/readme.md
=> fixed code identifier

virtualization/windowscontainers/TOC.md, virtualization/windowscontainers/manage-containers/container-storage.md
Not ready to merge yet, just a rough draft. Will resolve #673 
Looking for feedback from:
- @mattkur 
- @rpsqrd
PRs to the plang-issue673 branch are warmly welcomed
=> Starting container storage doc

virtualization/windowscontainers/manage-containers/container-networking.md
Basically the same problem that needs MAC address spoofing on Hyper-V also needs promiscuous mode on VMware, which might be worth a quick note here
=> Add a link to VMware for transparent networking

virtualization/windowscontainers/manage-containers/manage-serviceaccounts.md
This was a blocker for me in gMSA usage as described in issue #618
=> Add a note about SID/Name translation

virtualization/windowscontainers/about/faq.md
The original question sounded very doubtful and did not sound very "documentation" like.
=> Update faq.md - Edited a question

virtualization/windowscontainers/manage-containers/manage-serviceaccounts.md
Added specifics for steps to check before enabling anonymous SID/name translation.
=> Added details related to gMSA creation

virtualization/windowscontainers/kubernetes/common-problems.md, virtualization/windowscontainers/kubernetes/configuring-host-gateway-mode.md, virtualization/windowscontainers/kubernetes/getting-started-kubernetes-windows.md
Ran through the lesser-used pages with someone and updated the guide based on their feedback and issues.
=> Clarifies and fixes a few minor things in Kubernetes instructions.

virtualization/api/hypervisor-platform/funcs/WHvMapGpaRange.md, virtualization/api/hypervisor-platform/funcs/WHvUnmapGpaRange.md, virtualization/api/hypervisor-platform/hypervisor-platform.md
Signed-off-by: Justin Terry (VM) <juterry@microsoft.com>
=> Updates Map/UnmapGpaRange documentation

virtualization/windowscontainers/quick-start/quick-start-windows-server.md
My browsers nag about "this site is not safe".
I think it has to do with the non https image. Other websites in the docs don't have this problem
=> changed http to https for image

virtualization/windowscontainers/deploy-containers/system-requirements.md
Updating Nano Server doc on user/admin accounts
=> Updating Nano Server doc on user/admin accounts

virtualization/windowscontainers/deploy-containers/version-compatibility.md
Fixes #771 
@lisaguthrie can you review?
=> Updating version compatibility matrix for 1803

virtualization/api/vm-dump-provider/vm-dump-provider.md
Renames ApplyPendingSavedStateFileReplay in ApplyPendingSavedStateFileReplayLog.
=> Fix ApplyPendingSavedStateFileReplayLog link

virtualization/windowscontainers/manage-containers/container-storage.md
Exchanged underscores with hyphens to fix broken link to documentation
=> Adjusted link address

.openpublishing.redirection.json
Signed-off-by: Justin Terry (VM) <juterry@microsoft.com>
=> Removing WHvGetRunExitContextSize redirects

virtualization/hyper-v-on-windows/quick-start/connect-to-network.md
Add support statement for vSwitch over wireless card
=> Add support statement for vSwitch over wireless card

virtualization/api/hypervisor-platform/funcs/WHvGetPartitionProperty.md
=> Unsupported properties in WHvGetPartitionProperty

virtualization/windowscontainers/container-networking/architecture.md, virtualization/windowscontainers/container-networking/network-drivers-topologies.md
Updating docs so that people are aware of unsupported features.
=> added bullets for unsupported networking features

virtualization/hyper-v-on-windows/user-guide/custom-gallery.md
added command to generate file hash
=> added command to generate file hash

virtualization/windowscontainers/deploy-containers/system-requirements.md
Updated example link for .NET Core Nano Server Dockerfile so the link will not result in a 404.
=> Update .NET Core example link. Fixes #805

virtualization/windowscontainers/manage-containers/container-storage.md
- Use Codeblock for code-sample
- Fix list indentation
=> Fix formatting in container-storage.md

virtualization/windowscontainers/quick-start/quick-start-windows-10.md
Fixes https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/797
=> Add note about supported version numbers

virtualization/windowscontainers/container-networking/network-drivers-topologies.md
=> Fix spelling of assignmeny

virtualization/windowscontainers/manage-containers/manage-serviceaccounts.md
=> Fixed note

virtualization/hyper-v-on-windows/user-guide/setup-nat-network.md
Fixes #848: Corrects the sentence fragment for a section under [Setting up a NAT network](https://docs.microsoft.com/en-us/virtualization/hyper-v-on-windows/user-guide/setup-nat-network#docker-for-windows-linux-vm-and-windows-containers).
=> Fixes #848: Update the sentence fragment

virtualization/hyper-v-on-windows/quick-start/enable-hyper-v.md
The instructions are from the old Settings Dialog which can be reached clicking on the link added.
=> Windows settings menu update

virtualization/hyper-v-on-windows/user-guide/checkpoints.md
Two hyphens (an em dash) should be used to set off a parenthetical remark, not to separate a title from a description. See 
https://docs.microsoft.com/en-us/style-guide/punctuation/dashes-hyphens/emes. I recommend colons here.
=> Replace em dashes surrounded by spaces with colons

virtualization/hyper-v-on-windows/user-guide/checkpoints.md
Checkpoints.md has several spelling and grammar issues that I suggest fixing.
=> Update checkpoints.md for spelling and grammar

virtualization/windowscontainers/deploy-containers/linux-containers.md
=> Fix typos.

virtualization/windowscontainers/about/index.md
The first sentence ("This is our container") may be better ended with a colon to indicate it is talking about the picture that immediately follows, but I think a period still works. Feedback on this is welcome.
=> Add missing periods to two sentences

virtualization/windowscontainers/kubernetes/joining-windows-workers.md
https://github.com/coreos/flannel/issues/944#issuecomment-441182589
=> fix: can not create cbr0

virtualization/hyper-v-on-windows/user-guide/nested-virtualization-azure-virtual-network.md
Fixed RRAS config section to enable NAT and thus allow guest VMs to access the internet. Also just made some small edits. Fixed a grammatical mistake and removed the possibly as it almost made it seem like I wasn't sure if you could actually deploy 32bit VMs, cus you definitely can.
=> Edit RRAS section and proofread

virtualization/windowscontainers/quick-start/building-sample-app.md
Just removing an extra contain.
Thanks,
Antwon
=> Fixing a Typo

virtualization/hyper-v-on-windows/user-guide/nested-virtualization-azure-virtual-network.md
I had made some breaking changes to the doc. I have since redone my build of this and came up with a proper working solution to allow for LAN routing and nested VM internet connectivity. This required a major rewrite of the doc.
=> Major Rewrite

virtualization/windowscontainers/manage-docker/configure-docker-daemon.md
Update to Windows Server 2019 since the linked documentation mentions only Windows Server 2019 at the moment
=> Update to Windows Server 2019

virtualization/windowscontainers/quick-start/quick-start-windows-server.md
=> Fix markdown syntax

virtualization/windowscontainers/about/index.md, virtualization/windowscontainers/index.md
Replaced HTML formatting with markdown on index and about pages. Corrected two small errors
=> Formatting refactoring

virtualization/windowscontainers/container-networking/advanced.md, virtualization/windowscontainers/container-networking/architecture.md, virtualization/windowscontainers/container-networking/network-drivers-topologies.md, virtualization/windowscontainers/kubernetes/common-problems.md, virtualization/windowscontainers/kubernetes/getting-started-kubernetes-windows.md
* Added section on VFP NAT for overlay
* Made lack of IPv6 support more explicit
* added K8s FAQ for stale HNS objects with incompatible fields
=> k8s and windows networking updates

virtualization/windowscontainers/quick-start/quick-start-windows-10-linux.md
Signed-off-by: John Howard <jhoward@microsoft.com>
=> Bump LCOW to require RS5+

virtualization/hyper-v-on-windows/quick-start/quick-create-virtual-machine.md
doc update for issue #883
"Use Win10 version numbers, not release marketing names"
=> doc update for issue #883

hyperv-samples/benarm-powershell/GuestNameCheck.ps1
=> fix: hyperv-samples/benarm-powershell/GuestNameCheck.ps1

hyperv-samples/benarm-powershell/README.md
=> fix: hyperv-samples/benarm-powershell/README.md

virtualization/windowscontainers/quick-start/quick-start-windows-10-linux.md
- Resolve merge conflict
- Double word "the"
- Remove link locale
=> fix: virtualization/windowscontainers/quick-start/quick-start-windows-10-linux.md

.openpublishing.redirection.json, virtualization/hyper-v-on-windows/about/hyperv_on_windows.md, virtualization/hyper-v-on-windows/about/supported_guest_os.md, virtualization/hyper-v-on-windows/develop/make_mgmt_service.md, virtualization/hyper-v-on-windows/develop/powershell_snippets.md, virtualization/hyper-v-on-windows/develop/tlfs.md, virtualization/hyper-v-on-windows/quick-start/index.md, virtualization/windowscontainers/quick-start/index.md
- Replaces redirect files with entries in the openpublishing.redirect
- Tool formatted to 4 spaces indentation
- Manually adjusted entries because it doesn't turn relative to absolute
- fix "enable-hyperv" which was missing a "-" and wasn't working
=> chore: Generate Redirection file with MS Docs Authoring pack

windows-container-samples/PowerShellDSC_iis-10.0/README.md, windows-container-samples/nodejs/README.md
Inconsistent indentation for list items at the same level
=> fix: MD005/list-indent

virtualization/windowscontainers/deploy-containers/base-image-lifecycle.md, windows-server-container-tools/Debug-ContainerHost/README.md, windows-server-container-tools/VMM  - VM Template/readme.md
- Remove locale
- HTTP -> HTTPS
=> chore: Cleanup Microsoft links

prospective-docs/ic-history.md, virtualization/api/index.md, windows-server-container-tools/Wait-Service/readme.md
- No space after hash on atx style heading
- Automtically -> Automatically
- Add code fence langauge
=> fix: MD018/no-missing-space-atx

virtualization/windowscontainers/manage-containers/container-storage.md
Multiple spaces after hash on atx style heading
=> fix: MD019/no-multiple-space-atx

TODO.md, virtualization/hyper-v-on-windows/quick-start/connect-to-network.md, virtualization/hyper-v-on-windows/quick-start/create-virtual-machine.md, virtualization/hyper-v-on-windows/quick-start/try-hyper-v-powershell.md, virtualization/hyper-v-on-windows/reference/HyperVBackupApproaches.md, virtualization/hyper-v-on-windows/reference/hyper-v-requirements.md, virtualization/hyper-v-on-windows/user-guide/checkpoints.md, virtualization/hyper-v-on-windows/user-guide/make-integration-service.md, virtualization/hyper-v-on-windows/user-guide/nested-virtualization-azure-virtual-network.md, virtualization/hyper-v-on-windows/user-guide/setup-nat-network.md, virtualization/windowscontainers/kubernetes/common-problems.md, virtualization/windowscontainers/manage-docker/optimize-windows-dockerfile.md, virtualization/windowscontainers/troubleshooting.md, windows-container-samples/apache-http-php/README.md, windows-container-samples/apache-http/README.md, windows-container-samples/golang/README.md, windows-container-samples/iis-arr/Readme.md, windows-container-samples/mysql/README.md, windows-container-samples/nginx/README.md, windows-container-samples/python-django/README.md, windows-container-samples/redis/README.md, windows-container-samples/ruby/README.md, windows-container-samples/sqlite/README.md
Replace hard tabs.
Also added some missing code fence languages
=> fix: MD010/no-hard-tabs

virtualization/api/hypervisor-instruction-emulator/funcs/WhvEmulatorMemoryCallback.md, virtualization/windowscontainers/troubleshooting.md
Spaces inside code span elements
=> fix:  MD038/no-space-in-code

virtualization/windowscontainers/kubernetes/deploying-resources.md
Fixes https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/1130
=> Update obsolete links

virtualization/hyper-v-on-windows/user-guide/checkpoints.md
Fixes https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/1106 and https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/1111
=> Fix broken links

.gitignore, .vscode/extensions.json
Will suggest install of extension for authors using vs code
=> chore: Add MS Docs Authoring Pack

virtualization/windowscontainers/kubernetes/common-problems.md, virtualization/windowscontainers/kubernetes/network-topologies.md
=> added note on Azure UDR + host-gw clarification.

virtualization/windowscontainers/troubleshooting.md
Signed-off-by: Ameya Gawde <ameya.gawde@docker.com>
=> Avoid manual noting of dockerd pid

virtualization/windowscontainers/manage-containers/container-storage.md
Change note to annotation like in other places on this document
=> Change note to annotation

virtualization/windowscontainers/quick-start/building-sample-app.md
- Per #821 add command for directory navigation.
- Consistent Powershell cmdlets with syntax diagram docs.
=> Add command for directory navigation

virtualization/windowscontainers/kubernetes/common-problems.md
Fixing up the syntax to be used for netsh
=> Fixing up the netsh syntax

virtualization/hyper-v-on-windows/reference/hyper-v-requirements.md
Addresses issues https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/1318 and https://github.com/MicrosoftDocs/Virtualization-Documentation/issues/1011
=> Fixing typo

virtualization/windowscontainers/deploy-containers/deploy-containers-on-server.md
Rephrasing to influence less confusion akin #1269
=> Rephrase MCR migration and related experiences

virtualization/windowscontainers/manage-containers/hyperv-container.md
=> Typo: "thorough Docker" -> "through Docker"

virtualization/windowscontainers/quick-start/building-sample-app.md
=> duplicate word : 'comes'

virtualization/windowscontainers/manage-containers/gmsa-run-container.md
klist get krbtgt command will not work.
krbtgt is not correct SPN
The correct command is: klist get webapp01
=> Fix klist get krbtgt command;

windows-container-samples/ASP-NET-Blog-Application/README, windows-container-samples/ASP-NET-Blog-Application/db/Dockerfile
=> Update obsolete Docker image reference

virtualization/hyper-v-on-windows/user-guide/setup-nat-network.md
- Fixes #1046
- Mends GFM code fence info strings
- Regularizes code-blocks
- Uniforms spacing/indentation
=> Fix typo and uniform formatting

windows-server-container-tools/CleanupContainerHostNetworking/WindowsContainerNetworking-LoggingAndCleanupAide.ps1
Per requests #1264 and #1246; Trap disabled/misconfigured Hyper-V role as a warning instead.
=> Trap disabled/misconfigured Hyper-V role as a warning

hyperv-tools/Convert-WindowsImage/Convert-WindowsImage.psm1
Dismount-DiskImage doesn't support -PassThru in newer PowerShell versions. I added logic to test whether the -PassThru parameter is supported and if not, remove the -PassThru parameter from the command.
=> Updated Dismount-DiskImage to handle PassThru

virtualization/windowscontainers/deploy-containers/version-compatibility.md
fixed spacing and changed lang from batch to PowerShell where needed.
=> updated syntax for code blacks

virtualization/windowscontainers/about/overview-container-orchestrators.md
microservers seems wrong, should be microservices
=> fixed typo

virtualization/windowscontainers/deploy-containers/linux-containers.md
This article mislead me into thinking LCOWServer was an option when its not. It needs a nice big disclaimer like the one I added. Add such disclaimer as you wish, this one was only a suggestion, but a disclaimer is necessary.
=> clarified actual available usages

virtualization/windowscontainers/troubleshooting.md, windows-server-container-tools/wpr-profiles/HcsTraceProfile.wprp, windows-server-container-tools/wpr-profiles/readme.md
1) Created a WPR directory under tools.
2) Copied over the HCS WPR Profile
3) Updated the link in the docs.
=> Move WPR Profiles to Doc Repo

hyperv-tools/Convert-WindowsImage/Convert-WindowsImage.psm1
If Powershell isn't running as a native process, the calls to bcdedit and bcdboot will fail since system32 is redirected.
Using sysnative for bcdedit and bcdboot allows 32-bit Powershell to create a native bootable VHD on x64 or ARM64.
=> Use bcdedit from sysnative when Powershell running WoW

hyperv-samples/hcs-samples/JSON_files/HCS_Schema[Windows 10 SDK, version 1809].json, hyperv-samples/hcs-samples/JSON_files/HCS_Schema[Windows 10 SDK, version 1903].json, hyperv-samples/hcs-samples/JSON_files/HCS_Schema[Windows 10 SDK, version 2004].json
Add the virtualization-documentation HCS API samples with JSON files, which are used for HCS API configuration. Its repo is linked by "Schema Sample" in public HCS API documentation
=> add JSON files for HCS API configs

virtualization/windowscontainers/manage-containers/container-storage.md
Motivated by #1449 that also contains steps to reproduce. This will revert #1339.
=> Fix broken "storage-opts" configuration doc

virtualization/windowscontainers/about/index.md
Original: "...to support your app, your app, any runtimes or...". Removed the second "your app"
=> fixed a typo under "Container Images"

virtualization/api/TOC.md
=> Update TOC link

virtualization/api/TOC.md
=> Update WMI provider link

virtualization/windowscontainers/about/index.md
=> Update index.md (#1373)

virtualization/windowscontainers/container-networking/network-drivers-topologies.md
Changed my_transparent to my_l2bridge under section Creating a l2bridge network
=> changed my_transparent to my_l2bridge

virtualization/hyper-v-on-windows/user-guide/nested-virtualization.md
Update Nested virtualization with AMD information
=> Update Nested virtualization with AMD info

virtualization/hyper-v-on-windows/user-guide/nested-virtualization.md, virtualization/windowscontainers/deploy-containers/upgrade-windows-containers.md
adding AMD in nested virtualization page. Merging to Live
=> adding AMD in nested virtualization page. Merging to Live

virtualization/hyper-v-on-windows/user-guide/nested-virtualization.md
=> update date of article

virtualization/hyper-v-on-windows/user-guide/nested-virtualization.md
Update requirements based on processor
=> Update requirements based on processor

virtualization/hyper-v-on-windows/reference/tlfs.md
The name of the branch changed and broke most links.
=> Fixing TLFS links

virtualization/community/team-blog/2009/20090115-betaof-standalone-hypervisor-hyper-v-server-2008-r2.md
https://docs.microsoft.com/en-us/virtualization/community/team-blog/2009/20090115-betaof-standalone-hypervisor-hyper-v-server-2008-r2
https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/community/team-blog/2009/20090115-betaof-standalone-hypervisor-hyper-v-server-2008-r2.md
#PingMSFTDocs
=> TYpo "**Microsoft ～ 2008 R2."→"**Microsoft ～ 2008 R2**."

virtualization/community/team-blog/2009/20090302-fix-for-cert-error-on-hyper-v.md
https://docs.microsoft.com/en-us/virtualization/community/team-blog/2009/20090302-fix-for-cert-error-on-hyper-v
https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/community/team-blog/2009/20090302-fix-for-cert-error-on-hyper-v.md
#PingMSFTDocs
=> Typo "**Symptoms and resolution:  **"→"**Symptoms and resolution: **"

virtualization/community/team-blog/2009/20090817-hypervisor-footprint-debate-part-3-windows-server-2008-hyper-v-vmware-esxi-3-5.md
https://docs.microsoft.com/en-us/virtualization/community/team-blog/2009/20090817-hypervisor-footprint-debate-part-3-windows-server-2008-hyper-v-vmware-esxi-3-5
https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/community/team-blog/2009/20090817-hypervisor-footprint-debate-part-3-windows-server-2008-hyper-v-vmware-esxi-3-5.md
#PingMSFTDocs
=> Typo "****Disk ～ found:"→"**Disk ～ found:**"

virtualization/windowscontainers/manage-docker/optimize-windows-dockerfile.md
Start-Process is mentioned 7 times on the page
4 times it is correct casing: Start-Process
3 times it is incorrect casing (starts with lower case): start-Process which should be Start-Process
=> PowerShell cmdlet "start-Process" should be "Start-Process"

virtualization/community/team-blog/2009/20090512-hyper-v-in-ws08-r2-release-candidate-bringing-more-to-the-table.md
https://docs.microsoft.com/en-us/virtualization/community/team-blog/2009/20090512-hyper-v-in-ws08-r2-release-candidate-bringing-more-to-the-table
https://github.com/MicrosoftDocs/Virtualization-Documentation/blob/live/virtualization/community/team-blog/2009/20090512-hyper-v-in-ws08-r2-release-candidate-bringing-more-to-the-table.md
#PingMSFTDocs
=> Typo "**Processor ～ Migration  **"→"**Processor ～ Migration**"

virtualization/hyper-v-on-windows/user-guide/nested-virtualization.md
People copy the commands literally, so updated the PS commands to reflect vEthernet (VmNat) from ethernet
=> Updated the powershell command

virtualization/community/team-blog/2018/20180814-hyper-v-hyperclear-mitigation-for-l1-terminal-fault.md
I have corrected the processor type.
Close #1694
=> Fixed issue #1694

virtualization/community/team-blog/2017/20171219-tar-and-curl-come-to-windows.md
"it's" --> "its" in the line 21.
=> I solved the issue #1827.

virtualization/hyper-v-on-windows/user-guide/enable-nested-virtualization.md
Nested virtualization on AMD platforms isn't supported publicly untill WS2022/W11.
=> Update requirements for AMD platforms

virtualization/api/hypervisor-platform/hypervisor-platform.md
Rephrasing one sentence, and fixing Markdown errors (especially in tables).
=> Small fixes to WHP docs

virtualization/api/hcs/Reference/HcsPauseComputeSystem.md, virtualization/api/vm-dump-provider/reference/ReleaseSavedStateFiles.md, virtualization/hyper-v-on-windows/tlfs/datatypes/hv_device_interrupt_target.md, virtualization/hyper-v-on-windows/tlfs/hypercalls/HvCallEnablePartitionVtl.md, virtualization/hyper-v-on-windows/tlfs/hypercalls/HvCallEnableVpVtl.md
Remove the superfluous leading empty lines in these code blocks as they are shown when viewing on learn.microsoft.com.
=> Remove superfluous empty lines
