windows-server-container-tools/Install-ContainerHost/Install-ContainerHost.ps1

Without this fix, certs variable isn't set before it is used

Fix bug in runDockerDaemon.cmd

---

hyperv-tools/Convert-WindowsImage/Convert-WindowsImage.ps1

Forgive me for just jumping in; I hope it's alright ... I have successfully used this change locally a few times and previously spoken to Artem about using this fix. We're not entirely sure what changed to require being more selective with the parse specifier.

Issue #22: Convert-WindowsImage does not work with numeric editions.

---

hyperv-tools/Nested/Get-NestedVirtStatus.ps1

previously reported wrong build number, and always assumed host build was nested capable

fixed host build reporting bug

---

virtualization/hyperv_on_windows/user_guide/remote_host_management.md

Removed "Workgroup Only" only section and "Remove Hyper-V Host"
These two instruction sets accomplished the same thing as "Local Hyper-V host", just using different methods (GPO vs POSH), and advocated unnecessary things (disabling firewall). Added alternate commands to only only specific machines (more secure by default), but left the generic allow all instructions in place. Also corrected some readability issues.

Cleaned up non-domain access and added references

---

windows-server-container-tools/Install-ContainerHost/Install-ContainerHost.ps1

I tried to install docker, but an error occured while downloading the container image from OneGet.
```
PS C:\Windows\system32> C:\Install-ContainerHost.ps1 -HyperV
Querying status of Windows feature: Containers...
Feature Containers is already enabled.
Querying status of Windows feature: Hyper-V...
Feature Hyper-V is already enabled.
Waiting for Hyper-V Management...
Networking is already configured.  Confirming configuration...
Getting Container OS image (WindowsServerCore) version 10.0.10586.11 from OneGet (this may take a few minutes)...
Install-ContainerImage : Unable to download.
At C:\Install-ContainerHost.ps1:451 char:17
+ ...              Install-ContainerImage $imageName -Version $imageVersion
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ …
```

Fix container download

---

virtualization/windowscontainers/quick_start/manage_powershell.md

Removed: "Note that the output, an object representing the container, is stored in a variable $con. This variable is used in subsequent commands."
The variable $con is not used in the PowerShell code below, also the variable is not used in this part or the next one.

Removed sentence referring to non-existent code

---

demos/2015-BigBuild/BigBuild.ps1
demos/2015-Ignite-Whats-New/scripts/Convert-WindowsImage.ps1
demos/2015-Ignite-Whats-New/scripts/Demo.ps1
demos/2015-Ignite-Whats-New/scripts/WorkloadSetup.ps1
hyperv-samples/benarm-powershell/GuestNameCheck.ps1
hyperv-tools/Nested/Get-NestedVirtStatus.ps1
hyperv-tools/ic-update/offline-update-host.ps1
virtualization/hyperv_on_windows/quick_start/walkthrough_install.md
virtualization/hyperv_on_windows/quick_start/walkthrough_powershell.md
virtualization/hyperv_on_windows/user_guide/checkpoints.md
virtualization/hyperv_on_windows/user_guide/export_import.md
virtualization/windowscontainers/deployment/deployment.md
virtualization/windowscontainers/deployment/deployment_nano.md
virtualization/windowscontainers/deployment/docker_windows.md
virtualization/windowscontainers/management/container_networking.md
virtualization/windowscontainers/management/hyperv_container.md
virtualization/windowscontainers/management/manage_containers.md
virtualization/windowscontainers/management/manage_images.md
virtualization/windowscontainers/management/manage_resources.md
virtualization/windowscontainers/quick_start/container_setup.md

I just followed the PowerShell steps in https://msdn.microsoft.com/en-us/virtualization/hyperv_on_windows/quick_start/walkthrough_install and found a problem in the chapter **Install Hyper-V with PowerShell** in step 2. Putting that command line into a script results in an error message:
```
==> default: At C:\tmp\vagrant-shell.ps1:2 char:72
==> default: + ... -WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V â€“All
==> default: +                                                                      ~~~~
==> default: The string is missing the terminator: ".
==> default:     + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
==> default:     + FullyQualifiedErrorId : TerminatorExpectedAtEndOfString
==> default:  
```
I had a closer look and found …

Fix dashes in code examples

---

windows-server-container-tools/Install-ContainerHost/README.md

Creation of readme including parameters and usage for Install-ContainerHost.ps1.
The text was largely created from the following command:
`Get-Help .\Install-ContainerHost.ps1 -full | clip`
Output from clipboard was then formatted using Markdown for GitHub.

Create Install-ContainerHost.ps1 README.md

---

virtualization/windowscontainers/TOC.md
virtualization/windowscontainers/about/about_overview.md
virtualization/windowscontainers/about/container_ecosystem.md
virtualization/windowscontainers/about/faq.md
virtualization/windowscontainers/about/work_in_progress.md
virtualization/windowscontainers/containers_welcome.md
virtualization/windowscontainers/deployment/deployment.md
virtualization/windowscontainers/deployment/deployment_nano.md
virtualization/windowscontainers/deployment/docker_windows.md
virtualization/windowscontainers/deployment/system_requirements.md
virtualization/windowscontainers/docker/manage_windows_dockerfile.md
virtualization/windowscontainers/docker/optimize_windows_dockerfile.md
virtualization/windowscontainers/management/container_networking.md
virtualization/windowscontainers/management/hcs_powershell.md
virtualization/windowscontainers/management/hyperv_container.md
virtualization/windowscontainers/management/manage_data.md
virtualization/windowscontainers/management/manage_images.md
virtualization/windowscontainers/management/manage_resources.md
virtualization/windowscontainers/quick_start/manage_docker.md
virtualization/windowscontainers/quick_start/manage_docker_hyperv.md
virtualization/windowscontainers/quick_start/quick_start.md
virtualization/windowscontainers/quick_start/quick_start_configure_host.md
virtualization/windowscontainers/reference/app_compat.md

Just saw a typo and fixed all occurrences in the documentation repo.
contianer -> container

Fix typo: container

---

demos/2015-Ignite-Whats-New/scripts/WorkloadSetup.ps1
hyperv-samples/benarm-powershell/GuestNameCheck.ps1
hyperv-tools/Convert-WindowsImage/Convert-WindowsImage.psm1
hyperv-tools/Nested/Get-NestedVirtStatus.ps1
virtualization/windowscontainers/docker/manage_windows_dockerfile.md
virtualization/windowscontainers/management/container_networking.md
virtualization/windowscontainers/quick_start/container_setup.md
virtualization/windowscontainers/removed/dotnet35.md

This fixes all code examples to use double quotes and to make them copy-pastable for readers.

Fix quotes in code examples

---

windows-container-samples/windowsservercore/iis/Dockerfile

This fixes error when running container as follows "C:\Windows\system32\docker.exe: Error response from daemon: Container command 'ping localhost -t' not found or does not exist." This is occurring in the latest Tech Preview.

split ping command into arguments array

---

windows-container-samples/windowsservercore/python/README.md
windows-container-samples/windowsservercore/python/dockerfile

CMD ["py C:\hello.py"] results in an error "Command 'py C:\hello.py' no found".
Splitting it into separate arguments fixes the issue.

(minor) Python sample fix CMD to pass arguments separately

---

virtualization/windowscontainers/deployment/deployment.md
virtualization/windowscontainers/quick_start/quick_start_windows_server.md

While working through https://msdn.microsoft.com/en-us/virtualization/windowscontainers/deployment/deployment to reproduce the issue in #296 I found a small typo.
`s/teak/take/g`

Fix typo teak -> take

---

windows-server-container-tools/Install-ContainerHost/README.md

SkipDocker was removed in https://github.com/Microsoft/Virtualization-Documentation/commit/0477dc59592a498c8b8db24dc7fc70f222840864
NATSubnetPrefix was removed in https://github.com/Microsoft/Virtualization-Documentation/commit/75098699b789d39a362a8d03866dc2503ab51237
So I removed them both from the README.

Removed deprecated params from documentation

---

virtualization/windowscontainers/quick_start/quick_start_windows_server.md

When following these instructions on a fresh installation of TP5, I encounter an error: "invoke-webrequest : The response content cannot be parsed because the Internet Explorer engine is not available..." Adding -UseBasicParsing avoids trying to use IE.

Add -UseBasicParsing option to download commands

---

virtualization/hyperv_on_windows/user_guide/remote_host_management.md

I tried to follow the last section, "Manage a Hyper-V host outside your domain (or with no domain) ", with no success.
It seems that I need to enable the CredSSP server role on hyper-V host and run the original second and third command on the managing PC.
I'm running Windows 10 on both Hyper-V host and managing PC.

Issue with managing hyper-v host with no domain

---

virtualization/windowscontainers/deployment/deployment_nano.md

Previous didn't work so fixed to one that does, and simplified :-)

Updated Environment Variable save command line

---

windows-server-container-tools/DockerTLS/DockerCertificateTools.ps1

Wrapping the subject line in single quotes causes certificate authorization to fail.

Remove single quotes in subject line

---

virtualization/windowscontainers/management/container_networking.md

Typo in script
I get:
```
PS C:\Windows\system32> Set-Service docker -StartupType automaticac
Set-Service : Cannot bind parameter 'StartupType'. Cannot convert value "automaticac"
to type "System.ServiceProcess.ServiceStartMode". Error: "Unable to match the
identifier name automaticac to a valid enumerator name. Specify one of the following
enumerator names and try again:
Boot, System, Automatic, Manual, Disabled"
At line:1 char:33
+ Set-Service docker -StartupType automaticac
+                                 ~~~~~~~~~~~
+ CategoryInfo          : InvalidArgument: (:) [Set-Service], ParameterBindingExce
ption
+ FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Comm
ands.SetServiceCommand
```

Fix typo in script

---

windows-server-container-tools/Install-ContainerHost/Install-ContainerHost.ps1

This pull request updates Install-ContainerHost.ps1 to support the latest NanoServer image version (10.0.14300.1016). Because the version has changed on the SearchContainerImages.txt on http://go.microsoft.com/fwlink/?LinkID=746630&clcid=0x409 the scripts failed previously.

Update Install-ContainerHost.ps1 to latest NanoServer version

---

virtualization/windowscontainers/management/container_networking.md

This workaround is still sometimes needed after builds are upgraded. I adjusted the formatting so that I could copy & paste it into a PowerShell window and have it run without errors.

Fixing formatting around PowerShell snippet so you can copy & paste to run it

---

windows-server-container-tools/containers-azure-template/azuredeploy.json

There's an updated VHD that uses Docker v1.12, and has already run `docker pull Microsoft/windowsservercore`. We rebuilt all the images to use this version recently, and put an updated image on Azure. However, we didn't update the ARM template. This moves it to the known good version again.
This resolves #351 reported by @ddobric 
@taylorb-microsoft @enderb-ms do you want to give this a look before we merge it?

Switching to new image with updated daemon and microsoft/nanoserver image

---

windows-container-samples/windowsservercore/apache-http/Dockerfile

The current 2.4.18 link is broken. Besides, there is no specific reason to run 32 bit.
https://social.msdn.microsoft.com/Forums/en-US/dd32304c-06ac-4ad2-9acb-518602c75249/github-container-example-for-apache-produces-nonzero-code-255-on-tp5?forum=windowscontainers

update apache-http Dockerfile to use most recent version and change to 64 bit

---

virtualization/windowscontainers/deployment/deployment_nano.md

The final "docker ... run" commands on line 194 and 206 needs to start from the "microsoft/nanoserver" image, not "nanoserver". This is to be consistent with the rest of the article...

Change final docker run commands

---

virtualization/windowscontainers/quick_start/quick_start_windows_10.md

A few days I helped another Docker Captain to make Docker up and running in Windows 10. The problem was the wording 'technical preview' in the step to add the registry key.
He skipped this step as he thought this is only for the technical preview of Windows Server 2016.
So I think it is better to avoid this wording to make it more clear that this step is mandatory.

Avoid 'technical preview' wording in Windows 10 docs

---

virtualization/windowscontainers/quick_start/quick_start_windows_10.md

The latest `microsoft/nanoserver` base image is much smaller, so it's worth to update the sample output of `docker images`.

Update smaller base image size

---

virtualization/windowscontainers/quick_start/quick_start.md

I think it should say not shared with the other hyper-v container vs the windows server container sharing the kernel. If not correct there is something funny with this sentence.

Hyper-V Containers is not phrased correclty

---

windows-server-container-tools/Debug-ContainerHost/Debug-ContainerHost.ps1
windows-server-container-tools/Debug-ContainerHost/Windows.Tests.ps1

Fixing a bug in the installed KB detection logic. The update rollup number will be incrementing in the registry, so it's easier to check that instead of a list of specific KBs.
This also suppresses an error if no error/warning event logs are found :)

Fixing KB detection logic, suppressing error if no eventlogs found

---

windows-server-container-tools/DockerTLS/DockerCertificateTools.ps1

The "2h" version is no longer available and that link leads to a 404.  Switching to the "2j" version works.

Updating OpenSSL download link.

---

windows-server-container-tools/Debug-ContainerHost/Debug-ContainerHost.ps1
windows-server-container-tools/Debug-ContainerHost/README.md

This adds some new script output and also saves the warning & error logs to a CSV file. 
Here's examples of the new output:
```none
Showing output from: docker version
Client:
Version:      1.13.0-dev
API version:  1.25
Go version:   go1.7.1
Git commit:   cd0e399
Built:        Mon Oct 17 22:42:06 2016
OS/Arch:      windows/amd64
Server:
Version:      1.13.0-dev
API version:  1.25
Go version:   go1.7.1
Git commit:   cd0e399
Built:        Mon Oct 17 22:42:06 2016
OS/Arch:      windows/amd64
Showing output from: docker info
Containers: 13
Running: 0
Paused: 0
Stopped: 13
Images: 17
Server Version: 1.13.0-dev
Storage Driver: windowsfilter
Windows:
Logging Driver: json-file
Plugins:
Volume: local
Network: nat null overlay
Swarm: inactive
Default Isolation: hyperv
Kernel Version: 10.0 14393 …
```

Adding docker version info and error CSV file

---

windows-server-container-tools/Install-ContainerHost/Install-ContainerHost.ps1

Installation fails when installing on systems with an existing network that overlaps with the default Docker Nat of 172.16.0.0/12
This change allows the end user to set the Nat to something that wont clash, eg. 192.168.2.0/24

Add parameter to set net/mask for fixed-cidr

---

windows-server-container-tools/Debug-ContainerHost/Debug-ContainerHost.ps1

"Should Not Be Null" always returns "ok" even if $service -eq $null
tested it
```
$service = Get-Service | Where-Object {($_.Name -eq "Docker") -or ($_.Name -eq "com.Docker.Service")}
It "A Docker service is installed - 'Docker' or 'com.Docker.Service' " {
write-warning " is not null: $($service -ne $null)"
$service | Should Not Be Null
```
obviously "Null" is unknown to pester?

check for existing service corrected

---

windows-server-container-tools/Debug-ContainerHost/Debug-ContainerHost.ps1

It seems we need 351 as latest build for proper working Docker
See https://github.com/docker/for-win/issues/169

Update minimum working build for the Debug script

---

virtualization/windowscontainers/docker/manage_windows_dockerfile.md

I've noticed that in the sample Dockerfile has beend used the notation FROM windowsservercore this in a local build will result in an error due the fact that the local latest images is named microsoft/windowsservercore

Changed in the sample Dockerfile

---

windows-server-container-tools/Debug-ContainerHost/Debug-ContainerHost.ps1

When both Linux and Windows Docker are running, you get an error because one of the services is stopped. Succeeding test if 1 of the 2 services is running

Fixed the Docker Service check when more docker services are running

---

virtualization/windowscontainers/docker/manage_windows_dockerfile.md

I've noticed that, for example, in visual studio code the file is saved with .dockerfile extension and this obviously will not work. So to save people time when reading the documentation I thought this simple method could be added.

Added method to save Dockerfile with no extension

---

windows-server-container-tools/ServiceAccounts/README.md

When calling the New-CredentialSpec cmdlet the domain should set with the Get-ADDomain.
See CredentialSpec.psm1 for implementation details and examples.

Use Get-ADDomain instead of Get-Domain

---

virtualization/windowscontainers/quick_start/quick_start_windows_10.md

I suggested we move to the Docker v1.13 rc builds in #488, but #496 was merged instead. We should be using v1.13-rc as it's the most stable right now.
I'm testing this on another system and will merge it shortly

Change Docker from v1.14 to v1.13-rc2

---

virtualization/windowscontainers/docker/configure_docker_daemon.md

This is an alternative to #506 . We want to keep the quick start guide pointing to the most stable build, not the latest. This page has separate instructions to get to the latest build for developers.

Alternate to #506 updating manual install to v1.14-dev

---

windows-container-samples/vcbuildtools/Dockerfile
windows-container-samples/vcbuildtools/README.md

Here is a `Dockerfile` to build a Docker image with the Visual Studio C++ Build tools installed.
It would be great if we have something like `FROM microsoft/vcbuildtools:14.3` to run `msbuild` in a Container very easily.
How to use this image
```
docker build -t microsoft/vcbuildtools:14.3 .
```
Go into a folder with a simple C++ or other project with a solution file *.sln.
```
docker run -v "$(pwd):C:\code" microsoft/vcbuildtools:14.3 msbuild yourproject.sln /p:Configuration=Release
```
Example:
```
git clone https://github.com/StefanScherer/win-getaddrinfo
cd win-getaddrinfo
docker run -v "$(pwd):C:\code" microsoft/vcbuildtools:14.3 msbuild getaddrinfo.sln /p:Configuration=Release
dir getaddrinfo.exe
```

Proposal: Add microsoft/msbuild image

---

windows-server-container-tools/ServiceAccounts/README.md

While following the ServiceAccounts guide I had to change two minor steps to make them work.
I also had a problem with the first command `Add-KdsRootKey –EffectiveTime ((get-date).addhours(-10))` when I ran this directly on my DC machine. There was an error "Cannot create KDS Root Key - “Request is not supported”"
I found [this solution](http://serverfault.com/questions/543259/cannot-create-kds-root-key-request-is-not-supported) to run this from another domain joined machine, and it also worked for me.

Fix guide to create gMSA

---

windows-server-container-tools/Debug-ContainerHost/Debug-ContainerHost.ps1

`Get-ComputerInfo` is a slow way to determine whether you're on Windows 10 or Windows Server 2016. The only reason I was calling it was to decide which PowerShell cmdlet to use to check if the `Containers` role was installed. Checking if the cmdlet exists is much faster!

Speed up 'Has Containers feature installed' test

---

windows-server-container-tools/containers-azure-template/azuredeploy.json

I used the "Deploy to Azure" button at https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-server but found out that it only spins up a Windows Server 2016 with old Docker images rev 321
Now pulling microsoft/iis downloads the rev 693 windowsservercore base image, but that takes a long time.

Update azuredeploy imageVersion 2016.0.20170127

---

virtualization/windowscontainers/quick-start/quick-start-windows-server.md
windows-server-container-tools/containers-azure-template/README.md
windows-server-container-tools/containers-azure-template/azuredeploy.json
windows-server-container-tools/containers-azure-template/metadata.json

Testing the "Deploy to Azure" button in https://docs.microsoft.com/en-us/virtualization/windowscontainers/quick-start/quick-start-windows-server after PR #569 got merged, I found out that the azuredeploy.json taken is from master branch.
I have changed the links to use live branch instead.
I also have updated the description in the template.
And I have added a security rule for HTTPS port 443, might be useful in addition to HTTP port 80.

Use live branch for azuredeploy

---

windows-container-samples/ASP-NET-Blog-Application/docker-compose.yml

As https://github.com/docker/compose/issues/4106 states, the change to '2.1' fixes the following error, when running 'docker-compose up': ERROR: client version 1.2x is too old. Minimum supported API version is 1.2x, please upgrade your client to a newer version

Fixing ERROR: client version 1.2x is too old. Minimum supported API version is 1.2x

---

virtualization/windowscontainers/deploy-containers/system-requirements.md

Please read the latest metadata guidelines, I believe that ms.assetID is also no longer needed :) https://review.docs.microsoft.com/en-us/help/contribute/contribute-how-to-write-metadata?branch=master

removing ms.service metadata field

---

windows-server-container-tools/Debug-ContainerHost/Debug-ContainerHost.ps1
windows-server-container-tools/Debug-ContainerHost/README.md

Can you review @kallie-b or @JMesser81 ?
The network cleanup script doesn't recreate the NAT so you can get into a state where Docker thinks a nat is configured but it isn't. This helps detect that and adds steps in the README on how to fix it.

Adding check for missing NAT

---

virtualization/windowscontainers/troubleshooting.md

Signed-off-by: John Howard <jhoward@microsoft.com>
I added the wrong directory for the location of the stack dumps. Fixed :dog:

Fix typo on the dump directory for daemon

---

virtualization/windowscontainers/manage-containers/swarm-mode.md

Fix description of UDP port 4789 as noted in https://docs.docker.com/engine/swarm/swarm-tutorial/#open-protocols-and-ports-between-the-hosts

Fix Port 4789 to be UDP only

---

windows-server-container-tools/containers-azure-template/azuredeploy.json

the image version should be 'latest' to avoid errors due to future build deprecations.
This template is not getting deployed.

"imageVersion": "2016.0.20170127"

---

windows-server-container-tools/DockerTLS/DockerCertificateTools.ps1

I notice that the link for install SSL is broken, so I replace the broken URL for one on the same provider that is working. Thanks!

Update broken link for SSL installation

---

hyperv-tools/DiscreteDeviceAssignment/SurveyDDA.ps1

minus sign as a command line option must be ASCII, not a mathematical minus symbol

incorrect encoding of a minus sign

---

windows-server-container-tools/ServiceAccounts/CredentialSpec.psm1

(whether or not the daemon is running yet)
There's probably a tidier way to do this but the logic is correct.

Support relocated docker graph - fix #547

---

virtualization/hyper-v-on-windows/user-guide/setup-nat-network.md

**Summary:** This pull request swaps the order of two steps, with the hope of making them even smoother to follow.
When following the NAT setup steps, I would begin entering the `New-NetIPAddress` command, and when I got to the `InterfaceIndex` argument, I needed to clear that out to run the `Get-NetAdapter` command first. (And I remember making that same mistake a few months ago.) This pull request moves the step of finding the interface index to be before the step that asks you to enter it.
The other change, down in the Troubleshooting section, adds a needed space in the `InterfaceAlias` name, which I found when the non-space version returned an error.

Rearrange steps in NAT setup for convenience

---

virtualization/windowscontainers/TOC.md

I followed the tweet from MicrosoftDocs today and noticed the entry on the TOC was not highlighting.
So fixing the TOC to go to the right link so you can get the entry highlighted in the TOC.
Ideally, you'd have a master redirection file instead of doing the redirect on the files themselves so you'd get broken links in the build report when moving things around.

fix TOC not highlighting

---

windows-server-container-tools/Debug-ContainerHost/Debug-ContainerHost.ps1

Fix bug encountered when running script on Windows Server 2016 hosts where the log that is output to the  screen does not exist.  Added a path check to determine if the log exists before retrieving the content and outputting it to the screen.  If the log doesn't exist, the output declares that to the user.
Added logic to only display the last 100 lines of the log to the user in the terminal.  I found that outputting more than that risks pushing the test results out of the output that can be scrolled through in a powershell terminal.  The path is printed in the output and the user can refer to the file if they need more data.
Added output logic to provide the Windows OS Product Name and Build Label.  Some of the github issues on the moby/moby project indicate that some adverse behaviors …

Add path checking, output OS Build Label

---

virtualization/windowscontainers/quick-start/quick-start-images.md

Docker has revolutionized container management by adding automation. The documentation seems to advocate that manually creating an image is the first step into Docker. I could not disagree more. New users should be taught to embrace automation and understand the importance of standardization and repeatability. Therefore, I propose to remove the whole section.

Removed instructions for manual image creation

---

virtualization/windowscontainers/deploy-containers/version-compatibility.md

My chart was a bit confusing - there are actually differences between what works on WIndows 10 and Windows Server. Splitting this out to separate columns.

Clarify differences in isolation=hyperv support for Windows 10 vs Windows Server

---

virtualization/windowscontainers/manage-docker/optimize-windows-dockerfile.md

Currently the \ within ```in the '\' character is being used to line wrap``` from [windowscontainers/manage-docker/optimize-windows-dockerfile](https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-docker/optimize-windows-dockerfile#optimize-image-size) is not being displayed which makes reading the line strange.

Display \ character

---

demos/2016-Ignite-Dive-Into-Shielded-VMs/Ignite-demo-setup.ps1

creation of lab hyper-v switch must be done before the shieldinghelpervhd prep at it uses this virtual switch

fix missing switch in prep shieldinghelpervhd

---

virtualization/windowscontainers/manage-docker/configure-docker-daemon.md

Adding instructions to our docs for uninstalling and cleaning up after Docker on Windows 10 and Windows Server 2016.

Docker uninstall instructions

---

virtualization/windowscontainers/deploy-containers/system-requirements.md

A simple formatting fix to make the nanoserver warning more visible. Previously, the `*` was interpreted as a bullet point. Now, it's a warning block with a clickable link for the `*` in the table, in case it ever moves.

Makes a system requirement warning much more obvious.

---

windows-server-container-tools/ServiceAccounts/CredentialSpec.psm1

The existing behavior for setting the DnsName and DnsTreeName values would only work in a single-domain forest because the values were swapped. This fix corrects the values so that credential specs can be generated in multi-domain forests.

Fixed forest/domain name configuration in CredSpec

---

virtualization/windowscontainers/quick-start/Using-Insider-Container-Images.md

to provide consistency with Docker docs for EE Preview builds. Per discussions w @enderb. 
https://github.com/docker/docker.github.io/pull/5993 contains corresponding change to docs.docker.com to align with non-Insider builds

Change OneGet provider to DockerPreview

---

windows-container-samples/nginx/Dockerfile

Simple fix for the Dockerfile, just add a quotation mark for the vendor label.

Add quotation mark

---

virtualization/windowscontainers/kubernetes/getting-started-kubernetes-windows.md

I was just going to replace the MSDN term, but then I've noticed that several style guide principles were not being followed in this topic:
- [sentence case in headings](https://docs.microsoft.com/en-us/style-guide/scannable-content/headings#formatting-headings)
- [don't use we unless you're talking about a Microsoft recommendation](https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/w/we)
- [avoid future tense](https://docs.microsoft.com/en-us/style-guide/grammar/verbs#verb-tense)
- other minor rules

removed msdn + style guide fixes

---

virtualization/hyper-v-on-windows/quick-start/enable-hyper-v.md

The PowerShell syntax has a space between the parameter name and its value, not a colon.
The colon may also work, but still the common convention should be used to avoid confusion.

Distracting colon in PowerShell

---

virtualization/hyper-v-on-windows/quick-start/try-hyper-v-powershell.md

This seems to be a typo, but I tested to confirm. 
@VM returns error "A parameter is invalid. No switch can be found by given criteria."
$VM creates the VM as expected with parameters from the the $VM array.

Syntax error fix

---

virtualization/windowscontainers/kubernetes/getting-started-kubernetes-windows.md

There's also a guide on how to use acs-engine to deploy Windows. Rather than duplicating those steps, I'd like to link to them.
@gkudra-msft - does this look ok to you? I'm planning to update the samples on the acs-engine page to match the latest Kubernetes & Windows versions next

Adding link to acs-engine from Kubernetes getting started guide

---

virtualization/windowscontainers/manage-docker/configure-docker-daemon.md

Windows builds will soon be removed from master.dockerproject.org. This PR removes the section referencing use of those binaries and adds a reference to docs.docker.com for scripted installation.

Remove manual instructions

---

hyperv-tools/DiscreteDeviceAssignment/SurveyDDA.ps1

On line 122 "Where-Object{$_.StartingAddress -like $baseAdd}" was using an 'em' dash which PowerShell cannot parse, causing the script to fail.

Fixed dash character

---

virtualization/windowscontainers/manage-containers/container-storage.md

Former link was dead, fixed location of Docker Engine on Windows reference

Fixed location of Docker Engine on Windows reference

---

virtualization/hyper-v-on-windows/reference/tlfs.md

Replaced the Revision C link by the "/raw" github link to force the browser to download the file. Because on the mobile version github can't show you the PDF preview in the browser + to be consistent with the other revision links that are already using the /raw links.

Updated the Revision C link

---

virtualization/windowscontainers/quick-start/quick-start-windows-server.md

Since the specified tag is dotnetapp-nanoserver and the latest .NET Core version is 2.0, I've updated the Standard output to match the correct current output of the container, namely 2.0.

Updated the Standard output of the container

---

virtualization/windowscontainers/manage-docker/manage-windows-dockerfile.md

A bit of proofreading: added a '>' where one appeared to be missing.

Dropped a '>'

---

virtualization/windowscontainers/manage-docker/manage-windows-dockerfile.md

The MAINTAINED instruction is deprecated. It's preferred that you use the LABEL instruction to set a label for maintainer. This allows the information to be obtained via "docker inspect" and to be filtered using "-f".

Update the Dockerfile MAINTAINED instruction.

---

virtualization/windowscontainers/kubernetes/compiling-kubernetes-binaries.md

This PR updates the build script for generating Kubernetes windows binaries:
- the previous cmd didn't work ( KUBE_BUILD_PLATFORMS=windows/amd64 wasn't passed to build container as expected )
- sync with the latest build script sample documented in https://github.com/kubernetes/kubernetes/blob/master/build/README.md

update build script for generating k8s windows binaries

---

windows-container-samples/ASP-NET-Blog-Application/web/Dockerfile

Update Blogengine.net download url as old one is a redirect that does not point to binaries.

Update Blogengine.net download url

---

virtualization/windowscontainers/troubleshooting.md

Signed-off-by: John Howard <jhoward@microsoft.com>
Removes reference to daemon data. This hasn't been in docker for the longest time.

Remove daemon data reference

---

virtualization/windowscontainers/quick-start/quick-start-images.md

Windows Server Core images are now hosted on MCR and so are "foreign layers" to Docker hub.
For a new Docker user trying to use this quick start (like me) this seems like an error.
Adding a clarification that "foreign" layers are expected.

Clarify that Skipping foreign layer is success

---

virtualization/hyper-v-on-windows/quick-start/try-hyper-v-powershell.md

Seems there was a few problems with this example.
Firstly, the hash table was being passed with `$VM` so you'd get a default VM with the name `System.Collections.HashTable`.
Second, the switch name being found was `D` instead of `Default` since we were indexing in.

Fix problem with New-VM script example.

---

virtualization/windowscontainers/kubernetes/joining-windows-workers.md

Fixes #960 
The example is for Windows Server 2019, but showed the image name for Windows Server, Version 1803.

Update nanoserver image for Windows Server 2019

---

hyperv-tools/vmgallery/add-source.ps1
hyperv-tools/vmgallery/reset-sources.ps1

In some case, type of GalleryLocations value was REG_SZ.
It should be REG_MULTI_SZ for multiple values such as  GalleryLocations.
Added -Type dynamic parameter into each Set-ItemProperty calls.
The -Type parameter is documented below
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_registry_provider?view=powershell-6#dynamic-parameters

Add '-Type' parameter to prevent wrong registry value kind.

---

windows-container-samples/apache-http/Dockerfile

This pull request corrects an SSL / TLS error when building the image.
When building the image, Powershell `Invoke-WebRequest` command is used to download apache httpd binaries and .Net package. Without TLS set, the command fails.
Adding a security protocol to the  `Invoke-WebRequest` command solved the issue.
I also correct the URI to the apache httpd binaires which has moved from the previous URI.

Correcting SSL / TLS error when building image

---

virtualization/windowscontainers/about/index.md

Correct the doc of "About Windows container" mentions of "Azure Container Service" to be "Azure Kubernetes Service" instead.
Because Azure Container Service is deprecated, and all mentions of Kubernetes are using Azure Kubernetes Service as the official name of AKS. See also [AKS documentation landing page](https://docs.microsoft.com/en-us/azure/aks/).
Also correct the name of DockerHub, replaced with Docker's official "Docker Hub". Because the official name of Docker Hub **_is not_** DockerHub.

Update the deprecated Azure Container Services to Azure Kubernetes Service instead

---

windows-container-samples/Django/Dockerfile
windows-container-samples/Django/README.md
windows-container-samples/apache-http-php/Dockerfile
windows-container-samples/apache-http-php/README.md
windows-container-samples/python-django/Dockerfile
windows-container-samples/python-django/README.md
windows-container-samples/python/Dockerfile
windows-container-samples/python/README.md
windows-container-samples/sqlite/Dockerfile
windows-container-samples/sqlite/README.md

Hi,
today, I went over the windows-container-samples and noticed that some of them are not working anymore. For the ones that I fixed, this was because of old download links that were not available anymore, base images that were not correct anymore or because it could not use HTTPS URLs without this 'fancy' TLS1.2 command.
For the Dockerfiles that I touched, I also updated the product versions and the README files.
There are more samples that cannot be build, but I cannot fix them in appropriate time.

Fix some windows-container-samples

---

virtualization/windowscontainers/quick-start/quick-start-windows-10-linux.md
virtualization/windowscontainers/quick-start/quick-start-windows-10.md

This is a pull request from a Docker employee.
Note that our documentation uses both Docker Desktop and Docker Desktop for Windows. We prefer the former where the OS is clear from context, but the latter would be OK too.
Signed-off-by: Stephen Turner <stephen.turner@docker.com>

Docker for Windows is now Docker Desktop

---

hyperv-tools/Nested/Get-NestedVirtStatus.ps1

Currently, the error messages of multiple VMs are added to one variable `$VmCfgErrors`.
It shows same duplicate messages per VM as follows:
```
The virtual machine VM01 supports nested virtualization: NO
The following VM configuration errors have been detected:
This VM is not configured to expose virtualization extensions.
This VM is not configured to expose virtualization extensions.
This VM has one or more production checkpoints.
...
The virtual machine VM02 supports nested virtualization: NO
The following VM configuration errors have been detected:
This VM is not configured to expose virtualization extensions.
This VM is not configured to expose virtualization extensions.
This VM has one or more production checkpoints.
```
Expected messages are:
```
The virtual machine VM01 supports …
```

Split errors per VM: Get-NestedVirtStatus.ps1

---

virtualization/hyper-v-on-windows/quick-start/quick-create-virtual-machine.md

Oops,  the id of the H2s changed when the verbiage did, therefore the fragment hrefs broke.   this pull request fixes the fragments.

href fragment fix, id's of H2's changed when verbiage did

---

virtualization/windowscontainers/manage-containers/container-storage.md

Windows Server will convert the target-path of a mounted volume to lower-case.
This is important if you use a Linux container or a Windows container with a case-sensitive filesystem.
(I can provide more info about use cases, or where you get "unexpected" behaviour without this information., if necessary.)

Updates "Named Volumes" with note about case insensitivity

---

hyperv-samples/taylorb-wmi/xhypervbackup/xHyper-VBackup.cmdlets.psm1

VMName is not unique in Hyper-V. If there is more than one VM with the same name, all commandlets that accept a VMName will yield an error.

Allow using VmID instead of VMName

---

windows-server-container-tools/CleanupContainerHostNetworking/WindowsContainerNetworking-LoggingAndCleanupAide.ps1

I noticed that current code is using variable $adapter**s** inside of foreach loop which is incorrect.
It looks working fine on Windows Server 2016 because it does no list those non hardware interfaces without `-IncludeHidden` switch for `Get-NetAdapter` but because Windows Server 2019 does this need to be corrected.

Corrected network adapter unbinding

---

virtualization/windowscontainers/manage-containers/manage-serviceaccounts.md

The scope param for New-ADGroup is called -GroupScope, not -Scope. See https://docs.microsoft.com/en-us/powershell/module/addsadministration/new-adgroup?view=win10-ps#required-parameters

fix param name

---

virtualization/windowscontainers/manage-containers/manage-serviceaccounts.md

Addresses #1178 
Command syntax to add AD RSAT tools on modern versions of Windows 10 used the wrong verb and was missing the required `-Name` parameter.

Fixed Win10 AD RSAT cmdlet syntax

---

virtualization/landing-page/index.md

AKS has succeeded ACS, and in fact the existing link redirects to AKS. Updating the link and text.

Update landing page reference from ACS to AKS

---

windows-server-container-tools/ServiceAccounts/CredentialSpec.psm1

Having a way to create credential spec files without dependency on Docker running is very useful for provisioning or offline image (VHDX) building scenarios.
Hence the PR, to allow for credential spec files to be created without the dependency on Docker running or even being required at the time of credspec creation.
thnx

Support for an alternate credential specs output path via 'Path' parameter

---

virtualization/windowscontainers/deploy-containers/version-compatibility.md

Addressed the comment #1186. Extrapolated what the logical support for Windows 10 - 1903 host would be as the table seems to have been copied from the above Windows Server 2016 table.

Resolve odd Windows 10 - 1903 host table information.

---

virtualization/hyper-v-on-windows/index.md
virtualization/hyper-v-on-windows/quick-start/connect-to-network.md

index.md
The use of "\" instead of "/" on index.md was breaking links to other
documents while navigating through them on GitHub.
I also saw a page with a broken link to an image after navigating to one
of those links containing a "\".
connect-to-network.md contained a minor typo.

Fixed typos

---

windows-container-samples/directx/Dockerfile

Bumps version of WinMLRunner to `v1.2.1.1`
This fixes error
```
Model: C:/App/tiny_yolov2/model.onnx has an input type that isn't supported by WinMLRunner yet.
```

bump version of WinMLRunner for compatibility with model

---

virtualization/windowscontainers/manage-containers/manage-serviceaccounts.md

As per the documentation at https://docs.microsoft.com/en-us/powershell/module/addsadministration/add-adgroupmember
_"You can identify a new member by its distinguished name, GUID, security identifier, or SAM account name"_.
All computer objects in AD will have a SAM account name consisting of their netbios name, with a trailing '$'-sign. (e.g. ContainerHost01$)

Fix Add-AdGroupMember SamAccountName members

---

windows-server-container-tools/CleanupContainerHostNetworking/WindowsContainerNetworking-LoggingAndCleanupAide.ps1

Get-VMSwitch fails without Hyper-V feature installed. Need to check if Hyper-V feature is installed before calling the cmdlet.
Ran into the issue running the script with Get-VMSwitch cmdlet on Windows Server 2019 server core where Hyper-V feature wasn't installed.

need to check if Get-VMSwitch cmdlet is available

---

hyperv-tools/Convert-WindowsImage/Convert-WindowsImage.psm1

Convert-WindowsImage currently skips ARM64 images since there had been no virtualization platform for them.  Now that HyperV for ARM64 clients is available in Insider builds, that restriction should be removed.

Update Convert-WindowsImage to allow creating ARM64 VHDX files

---

virtualization/windowscontainers/manage-docker/configure-docker-daemon.md

On section subheading "Clean up Docker data and system components",  "Get-HNSNetwork | Remove-HNSNetwork" cmdlet works fine on Windows 10, but it never works on Windows Server 2016. You should use  "Get-ContainerNetwork | Remove-ContainerNetwork" in place of "Get-HNSNetwork | Remove-HNSNetwork" on Windows Server 2016. My customer faced this issue on Windows Server 2016 and complained that this article was not correct.

"Get-HNSNetwork" cmdlet never works on WS2016

---

virtualization/community/team-blog/2017/20170706-vagrant-and-hyper-v-tips-and-tricks.md

Hey all! :wave: I am one of the maintainers of the HashiCorp Vagrant project. I noticed this handy tips and tricks document, and wanted to update it to use the latest Vagrant box that we recommend people use. `hashicorp/precise64` is a very old box these days, and will likely cause issues for some users. We have a new box that is Ubuntu 18.04 LTS that we recommend folks use when getting started with Vagrant. I also cleaned up some of the trailing whitespace in the document while I was in there. Hope that this helps. Thanks!

Update Vagrant box in tips and tricks to latest supported version

---

virtualization/windowscontainers/container-networking/architecture.md

Adds a link to the HNS Powershell module in the `Container Network Management with Host Network Service` section.
Fixes #1539

Adds link to the HNS module

---

virtualization/windowscontainers/manage-containers/container-storage.md
virtualization/windowscontainers/manage-containers/persistent-storage.md

While CSV works in some cases it is not a regularly validated scenario and does not have end-to-end support with orchestrators or failover clustering so we do not recommend/support it in production.

Clarifying support on cluster shared volumes (CSV)

---

virtualization/api/hcs/Reference/APIOverview.md

Removed implementation detail from the Process Execution section.  The process APIs allow for asynchronous execution and client should not assume that the API calls are synchronous or asynchronous as this may change in future OS releases.

Update Process Execution section.

---

virtualization/windowscontainers/deploy-containers/version-compatibility.md

There were some errors with the version names in the compatibility matrix. Also added a Windows 11 matrix and a note about the new support for process isolation on Win11.

Fixing version compatibility matrix + Windows 11

---

virtualization/hyper-v-on-windows/tlfs/hypercall-interface.md

TLFS has an off-by-one bug for the last reserved field, which it defines as
being bits 64:60.  The same section states "The input field 64-bit value
called a hypercall input value.", i.e. bit 64 doesn't exist.
Note: published TLFS versions up to 6.0b don't have this issue.
Reported-by: Sean Christopherson <seanjc@google.com>
Signed-off-by: Vitaly Kuznetsov <vkuznets@redhat.com>

TLFS: Fix off-by-one bug in hypercall parameters definition

---

virtualization/hyper-v-on-windows/tlfs/hypercall-interface.md

TLFS mentions that bit 27-31 must be set to zero while doing a
hypercall. But this is not true, when we are trying to a hypercall in the
nested hypervisor setup. Bit 31 must be set if you want to do hypercall
to L0 hypervisor from a L2 guest.
Reported-by: Anirudh Rayabharam <anirudh.rayabharam@microsoft.com>
Signed-off-by: Jinank Jain <jinankjain@microsoft.com>

TLFS: Fix a bug in hypercall parameter definition for nested hypervisor

---

virtualization/hyper-v-on-windows/tlfs/vsm.md

DR4 and DR5 are alias registers at best and should not be described as shared.

Correct shared register description

---

virtualization/windowscontainers/TOC.md
virtualization/windowscontainers/quick-start/lift-shift-to-containers copy.md
virtualization/windowscontainers/quick-start/lift-shift-to-containers.md

This commit removes a link from TOC to a duplicate of gMSA entry. It also adds the new Lift and Shift content.

fix to gmsa TOC and new LiftShift content

---

hyperv-tools/DiscreteDeviceAssignment/SurveyDDA.ps1

The HyperV stack allows you to DDA legacy PCI express endpoints when devices are specific types of graphics controllers.
For historical reasons, these GPUs often report themselves as legacy devices for compatibility with BIOS code.

Update SurveyDDA.ps1 to allow certain legacy VGA devices

---

virtualization/windowscontainers/manage-containers/container-security.md

Addresses a customer question around the use of ContainerUser as the account the entrypoint uses with service monitor.

docs: add new section for windows services

---

virtualization/windowscontainers/deploy-containers/version-compatibility.md

This commit updates the Windows Containers compatibility tables to include the newly released WS2025 server [1] and images [1]. 
__
[1] https://www.microsoft.com/en-us/evalcenter/download-windows-server-2025
[2] https://hub.docker.com/r/microsoft/windows-servercore

windows containers: update version compatibility to include WS2025

---

virtualization/windowscontainers/manage-containers/container-base-images.md

This commit updates the wording on base images and server releases to current WS2025.
Refs:
- https://www.microsoft.com/en-us/evalcenter/download-windows-server-2025
- https://hub.docker.com/r/microsoft/windows-servercore

windows containers: update base image information to current WS2025

---

virtualization/api/hypervisor-platform/hypervisor-platform.md

WHP docs should point to where relevant headers can be ingested and what where the required DLL can be located to make it easier for folks onboarding or ramping up. 
Viewed with markdown viewer in VSCode to verify that there were no formatting issues.

WHP docs tweak - add notes about where to find relevant headers and dlls
